name: Main test
on: [push]
jobs:
  container-job:
    name: dogs
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: host.docker.internal
          POSTGRES_PORT: 2525
          POSTGRES_USER: dog
          POSTGRES_PASSWORD: gavgav
          POSTGRES_DB: konura
        ports:
          - 2525:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Wait for Postgres
        run: sleep 10
      - name: Import database dump
        run: |
          PGPASSWORD=gavgav psql -U dog -d konura -f dump.sql
      - name: Python installation
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

  linter_for_main:
    name: Flake8 app.py & test_api.py
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0
    - name: Flake8 app.py & test_api.py
      run: flake8 app.py & flake8 test_api.py

  linter_for_model:
    name: Flake8 model.py
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0
    - name: Flake8
      run: flake8 model.py

  tests_for_api:
    name: Tests test_api.py
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: host.docker.internal
          POSTGRES_PORT: 2525
          POSTGRES_USER: dog
          POSTGRES_PASSWORD: gavgav
          POSTGRES_DB: konura
        ports:
          - 2525:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Wait for Postgres
        run: sleep 10
      - name: Import database dump
        run: |
          PGPASSWORD=gavgav psql -U dog -d konura -f dump.sql
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.9.0
          pip install -r requirements.txt
      - name: Run tests
        run: python3 app.py & pytest test_api.py
